### ISSUE TITLE
Cannot start the app.js

### ISSUE THREAD

**Issue by HoYinChung** [SovGVD/nodetello#2]
when I try to start the `app.js` with `node app.js`
the following error happens: 
```
(node:25512) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
tello_control listening 0.0.0.0:51615
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'D:\nodetello\video\1535987841691.video.h264'
Emitted 'error' event at:
    at lazyFs.open (internal/fs/streams.js:273:12)
    at FSReqWrap.oncomplete (fs.js:139:20)
```

Hope to know if I am having an issue or not, any way to fix that? Thanks

**Comment by markusvankempen** [comment]
Just create a ./video directory it the nodetello folder

**Comment by HoYinChung** [comment]
Thanks
